# these are needed to run Spotify on Wayland
# WaylandWindowDecorations is needed to get the Spotify systray icon added to the eww systray widget.
[spotify]
extra_arguments = ["--enable-features=WaylandWindowDecorations", "--enable-features=UseOzonePlatform", "--ozone-platform=wayland"]
