# this only works when put into /etc/spotify-launcher.conf?
#
[spotify]
extra_arguments = ["--enable-features=WaylandWindowDecorations", "--enable-features=UseOzonePlatform", "--ozone-platform=wayland"]
